# Sequenzdiagramm

```plantuml
@startuml

!theme mars

title Wohnung.zimmerUmbauen(int, String, ArrayList<Moebel>)

participant Main
participant "Wohnung1:Wohnung"
participant "Zimmer0:Zimmer"
participant Moebel
participant "Schlafzimmer0:Schlafzimmer"
participant "Badezimmer0:Badezimmer"
participant "Wohnzimmer0:Wohnzimmer"
participant "Zimmer1:Zimmer"

Main -> "Wohnung1:Wohnung" : zimmerUmbauen(0, "Schlafzimmer", schlafzimmerMoebel)
/'schlafzimmerMoebel = [Bett bett1, Bett bett2, Moebel spiegel]'/
"Wohnung1:Wohnung" -> "Wohnung1:Wohnung" : getAnzahlZimmer()
"Wohnung1:Wohnung" -> "Wohnung1:Wohnung" : getZimmerListe()
"Wohnung1:Wohnung" -> "Zimmer0:Zimmer" : getTyp()
"Wohnung1:Wohnung" -> "Zimmer0:Zimmer" : leeren()
loop for (Moebel moebel : zimmer.moebelListe)
    "Zimmer0:Zimmer" -> Moebel : ausZimmerNehmen()
end
alt typ == "Schlafzimmer"
"Wohnung1:Wohnung" -> "Schlafzimmer0:Schlafzimmer" : new Schlafzimmer(betten)
"Schlafzimmer0:Schlafzimmer" -> Zimmer : super()
Zimmer -> Zimmer : setTyp("Schlafzimmer")
"Schlafzimmer0:Schlafzimmer" -> "Schlafzimmer0:Schlafzimmer" : setMaxBetten(betten.size())
loop for (Bett bett : schlafzimmer0.betten)
"Schlafzimmer0:Schlafzimmer" -> "Schlafzimmer0:Schlafzimmer" : bettHinzufuegen(bett)
end
else typ == "Badezimmer"
"Wohnung1:Wohnung" -> "Badezimmer0:Badezimmer" : new Badezimmer(wc, dusche, lavabo)
"Badezimmer0:Badezimmer" -> Zimmer : super()
Zimmer -> Zimmer : setTyp("Badezimmer")
"Badezimmer0:Badezimmer" -> "Badezimmer0:Badezimmer" : setWc(wc)
"Badezimmer0:Badezimmer" -> "Badezimmer0:Badezimmer" : setDusche(dusche)
"Badezimmer0:Badezimmer" -> "Badezimmer0:Badezimmer" : setLavabo(lavabo)
else typ == "Wohnzimmer"
"Wohnung1:Wohnung" -> "Wohnzimmer0:Wohnzimmer" : new Wohnzimmer(sofas, couchtische)
"Wohnzimmer0:Wohnzimmer" -> Zimmer : super()
Zimmer -> Zimmer : setTyp("Wohnzimmer")
"Wohnzimmer0:Wohnzimmer" -> "Wohnzimmer0:Wohnzimmer" : setMaxCouchtische(couchtische.size())
"Wohnzimmer0:Wohnzimmer" -> "Wohnzimmer0:Wohnzimmer" : setMaxSofas(sofas.size())
loop for (Couchtisch couchtisch : wohnzimmer0.couchtische)
"Wohnzimmer0:Wohnzimmer" -> "Wohnzimmer0:Wohnzimmer" : couchtischHinzufuegen(couchtisch)"
end
loop for (Sofa sofa : wohnzimmer0.sofas)
"Wohnzimmer0:Wohnzimmer" -> "Wohnzimmer0:Wohnzimmer" : sofaHinzufuegen(sofa)"
end
else
"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : new Zimmer()
"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : setTyp(typ)
end

loop (Moebel moebel : sonstigeMoebel)
"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : moebelHinzufuegen(moebel)
"Zimmer1:Zimmer" -> Moebel : einrichten(this)
Moebel -> Moebel : setZimmer(zimmer)
end

"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : setAnzahlLampen(zimmer0.getAnzahlLampen())
"Zimmer1:Zimmer" -> "Zimmer0:Zimmer" : getAnzahlLampen()
"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : setLichtAn(false)
"Wohnung1:Wohnung" -> "Zimmer1:Zimmer" : setAnzahlFenster(zimmer0.getAnzahlFenster())
"Zimmer1:Zimmer" -> "Zimmer0:Zimmer" : getAnzahlFenster()

"Wohnung1:Wohnung" -> Main : return alteMoebel
@enduml
```